// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SplashTrainer.Data;

#nullable disable

namespace SplashTrainer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SplashTrainer.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SwimmingPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SwimmingPlanId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("SplashTrainer.Models.PlanExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("ExerciseTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SwimmingExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SwimmingPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SwimmingExerciseId");

                    b.HasIndex("SwimmingPlanId");

                    b.ToTable("PlanExercises");
                });

            modelBuilder.Entity("SplashTrainer.Models.SwimmingExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Distance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SwimmingExercises");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Category = "Nogi",
                            Description = "Deskę trzymaj na wyskości ud, na prostych rękach. Skup się na stabilnym tempie i równm ułożeniu bioder.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Praca nóg z deską",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Nogi",
                            Description = "Utrzymuj równą pracę nóg na całym dystansie.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Naprzemienne kopnięcia bez deski",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Nogi",
                            Description = "Pamiętaj o minimalnie ugiętych kolanach i o tym żeby nie wychodziły nad taflę wody oraz o poprawnie ułożonych biodrach.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Wysokie kopnięcia nóg",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Nogi",
                            Description = "Złącz ręce za głową w strzałce. Trzymaj brzuch napięty oraz pilnuj, aby kolana nie wychodziły nad wodę.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Kopnięcia nóg z rękoma w strzałce",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Nogi",
                            Description = "Skup się na izolowaniu jednej nogi przed 25m.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Praca jedną nogą",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Ręce",
                            Description = "Skup się na technice naprzemiennej pracy ramion.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Praca rąk z pullboyem",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Ręce",
                            Description = "Utrzymuj symetryczną pracę rąk oraz stabilny korpus. Pamiętaj aby dłoń wkładać do wody zaczynając od małego palca, a wyciągać z wody zaczynając od kciuka.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Naprzemienne praca rąk",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Ręce",
                            Description = "Zacznij od ruchu jedną ręką - drugą trzymaj wzdłuż ciała. Po wykonaniu ruchu, klaśnij delikatnie nad wodą, nad nogami. Trzymaj wyprostowane ręce. Następnie powtórz po ruchu drugiej ręki.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Naprzemiennie z klaśnięciem",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Ręce",
                            Description = "Koncentruj się na delikatnym i precyzyjnym wejściu dłoni do wody - od małego palca. Wyjście zaczyna się od kciuka. Pamiętaj, aby nie uginać łokci.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Ćwiczenie na precyzję wejścia rąk",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Ręce",
                            Description = "Pracuj jedną ręką prze 50m, utrzymując stabilną pozycję ciała.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Praca jedną ręką",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Koordynacja",
                            Description = "Pamiętaj o synchronizacji pracy rąk i nóg.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Równoczesna praca rąk i nóg",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Koordynacja",
                            Description = "Wykonuj naprzemiennie ruch rękoma. Zaczynaj parcę drugą ręką dopiero, gdy pierwsza znajdzie się wzdłuż bioder.Utrzymuj równomierny rytm przez cały cykl.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dokładanka z rękoma wzdłuż ciała",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Koordynacja",
                            Description = "Wykonuj naprzemiennie ruch rękoma. Po każdym ruchu ręką, zatrzymaj je przy biodrach na 4 sekundy. Utrzymuj równomierny rytm przez cały cykl.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dokładanka z rękoma wzdłuż ciała + zatrzymanie",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Koordynacja",
                            Description = "Umieść jedą rękę prostą za głową, a drugą wzdłuż ciała. Wykonuj ruchy naprzemiennie. Po każdym ruchu zatrzymanie rąk na 4 sekundy. Zachowaj pełną kontrolę nad pracą nóg i rąk.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Zegar",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Koordynacja",
                            Description = "Utrzymuj biodra wysoko i spęty brzuch, podczas przekładania obu rąk. Dostosuj tempo do wydłużonych ruchów rąk.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Praca obu rąk na raz",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Wytrzymałość",
                            Description = "Skup się na równomiernym oddechu i rytmie.",
                            Distance = 200,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Pływanie w równym tempie",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Wytrzymałość",
                            Description = "Płyń na 75% możliwości przez 100m, odpoczywaj przez 20 sekund.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Wytrzymałość na długim dystansie",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Wytrzymałość",
                            Description = "Wdychaj co trzeci cykl, utrzymując stabilne tempo.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Serie z kontrolą oddechu",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Wytrzymałość",
                            Description = "Zmieniaj tempo co 25m, przechodząc z szybkiego na wolne.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Naprzemienne tempo",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Wytrzymałość",
                            Description = "Płyń w stałym tempie, kontrolując oddech i pracę ciała.",
                            Distance = 250,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Wydłużone dystanse w równym rytmie",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Szybkość",
                            Description = "Daj z siebie wszystko na krótkim odcinku.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Sprint na krótkim dystansie",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Szybkość",
                            Description = "Zmieniaj intensywność co 25m. Zacznij od średniego tempa.",
                            Distance = 75,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Naprzemienne sprinty",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Szybkość",
                            Description = "Ćwicz szybki start i dynamiczne nawroty.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Starty z nawrotem",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Szybkość",
                            Description = "Maksymalna intensywność na każdym 25m.",
                            Distance = 25,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Skrócone serie sprintów",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Szybkość",
                            Description = "Utrzymuj najwyższą intensywność przez cały dystans.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Długie sprinty",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Nogi",
                            Description = "Utrzymuj biodra na powierzchni wody, staraj się trzymać je na jednym poziomie.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Naprzemienne kopnięcia z deską",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Nogi",
                            Description = "Utrzymuj równą pracę nóg na całym dystansie.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Naprzemienne kopnięcia bez deski",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Nogi",
                            Description = "Wykonuj energiczne i szybkie kopnięcia. Pamiętaj o minimalnie ugiętych kolanach i o poprawnie ułożonych biodrach.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Wysokie kopnięcia nóg",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Nogi",
                            Description = "Złącz ręce za głową w strzałce. Trzymaj brzuch napięty oraz pilnuj, aby stopy nie wychodziły nad wodę.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Kopnięcia nóg z rękoma w strzałce",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Nogi",
                            Description = "Skup się na izolowaniu jednej nogi przed 25m.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Praca jedną nogą",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Ręce",
                            Description = "Trzymaj biodra stabilnie i skup się na wiosłowaniu.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Praca rąk z pullboyem",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Ręce",
                            Description = "Wykonuj ruch jedną ręką. Drugą trzymaj deskę. Utrzymuj stabilny korpus.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Naprzemienne praca rąk z deską",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Ręce",
                            Description = "Skup się na pracy jedną ręką przez 50m. Możesz użyć deski.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Praca jedną ręką",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Ręce",
                            Description = "Zwróć uwagę na synchronizację ruchów z regularnym oddechem.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Synchronizacja rąk z oddechem",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Ręce",
                            Description = "Sięgaj ręką jak najdalej, odkręcaj bark. Koncentruj się na pełnym zakresie ruchu i efektywności pracy rąk.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Wydłużenie cykli pracy rąk",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Koordynacja",
                            Description = "Dostosuj tempo nóg do ruchów rąk.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Synchronizacja rąk i nóg",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Koordynacja",
                            Description = "Wykonuj naprzemiennie ruch rękoma. Zaczynaj parcę drugą ręką dopiero, gdy pierwsza znajdzie się wyprostowana z przodu obok drugiej ręki.Utrzymuj równomierny rytm przez cały cykl.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dokładanka z rękoma wyprostowanymi z przodu",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Koordynacja",
                            Description = "Wykonuj naprzemiennie ruch rękoma. Po każdym ruchu ręką, zatrzymaj je z przodu na 4 sekundy. Utrzymuj równomierny rytm przez cały cykl.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dokładanka z rękoma wyprostowanymi z przodu + zatrzymanie",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Koordynacja",
                            Description = "Umieść jedą rękę prostą za głową, a drugą wzdłuż ciała. Wykonuj ruchy naprzemiennie. Po każdym ruchu zatrzymanie rąk na 4 sekundy. Zachowaj pełną kontrolę nad pracą nóg i rąk.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Zegar",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Koordynacja",
                            Description = "Umieść jedą rękę prostą za głową, a drugą wzdłuż ciała. Wykonuj ruchy naprzemiennie. Po każdym ruchu, klepnij ręką w wodę. Zachowaj pełną kontrolę nad pracą nóg i rąk.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Zegar + klepnięcie",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Wytrzymałość",
                            Description = "Skup się na utrzymaniu równomiernego oddechu.",
                            Distance = 200,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Pływanie w równym tempie",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Wytrzymałość",
                            Description = "Odpoczywaj 15 sekund po każdym dystansie 50m.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Wytrzymałość z krótkimi przerwami",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Wytrzymałość",
                            Description = "Wdychaj co trzeci ruch ramion.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Serie z kontrolą oddechu",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Wytrzymałość",
                            Description = "Przechodź między szybkim a wolnym tempem.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Naprzemienne tempo co 25m",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Wytrzymałość",
                            Description = "Utrzymuj spokojny oddech i równomierne tempo.",
                            Distance = 250,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Długie dystanse w równym rytmie",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Szybkość",
                            Description = "Odpoczywaj 30 sekund między każdym sprintem.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Sprinty na krótkim dystansie",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Szybkość",
                            Description = "Zmieniaj intensywność co 25m.",
                            Distance = 75,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Naprzemienne sprinty i pływanie luźne",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Szybkość",
                            Description = "Trenuj dynamiczne starty i nawroty z maksymalną intensywnością.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dynamiczne starty z nawrotem",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Szybkość",
                            Description = "Utrzymuj najwyższą intensywność na całym dystansie.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Sprint",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Szybkość",
                            Description = "Staraj się utrzymać maksymalne tempo przez cały dystans.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Maksymalna prędkość na dłuższym dystansie",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Nogi",
                            Description = "Skup się na szerokim ruchu nóg, przypominającym żabę. Pamiętaj aby kolana nie były za daleko od siebie.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Naprzemienne kopnięcia z deską",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Nogi",
                            Description = "Po każdym ruchu, trzymaj złączone nogi, dopkóki nie stracisz całej prędkości. Pamiętaj o dokładnym prostowaniu nóg po każdym ruchu.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Naprzemienne kopnięcia nóg + wyleżenie",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Nogi",
                            Description = "Wykonuj naprzemiennie mały okrąg nogami, a następnie pełen cykl - duży okrąg.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Małe i duże kółeczka",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 63,
                            Category = "Nogi",
                            Description = "Złącz ręce za głową w strzałce. Trzymaj brzuch napięty oraz pilnuj, aby stopy nie wychodziły nad wodę.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Kopnięcia nóg z rękoma w strzałce",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Nogi",
                            Description = "Skup się na izolowaniu jednej nogi przed 25m.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Praca jedną nogą",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Ręce",
                            Description = "Trzymaj nogi stabilnie i skup się na ruchu rąk.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Ruchy rąk z pullboyem",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Ręce",
                            Description = "Skup się na pełnym zakresie ruchu jednej ręki.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Praca jedną ręką na zmianę",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Ręce",
                            Description = "Dostosuj rytm rąk do odpowiedniego momentu oddechu.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Synchronizacja rąk z oddechem",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Ręce",
                            Description = "Skup się na pracy rąk. Wykomując nogi do kraula, łatwiej skupisz się na technice pracy rąk do żaby.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Żabo-Kraul",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Ręce",
                            Description = "Skup się na spokojnym i pełnym zakresie ruchu.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Wydłużone cykle pracy rąk",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Koordynacja",
                            Description = "Dostosuj rytm nóg do ruchu rąk.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Synchronizacja nóg i rąk",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Koordynacja",
                            Description = "Wykonuj naprzemiennie ruch rękoma. Zaczynaj parcę drugą ręką dopiero, gdy pierwsza znajdzie się wyprostowana z przodu obok drugiej ręki.Utrzymuj równomierny rytm przez cały cykl.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dokładanka z rękoma wyprostowanymi z przodu",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Koordynacja",
                            Description = "Wykonuj naprzemiennie ruch rękoma. Po każdym ruchu ręką, zatrzymaj je z przodu na 4 sekundy. Utrzymuj równomierny rytm przez cały cykl.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dokładanka z rękoma wyprostowanymi z przodu + zatrzymanie",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 73,
                            Category = "Koordynacja",
                            Description = "Po każdym cyklu (kopnięcie nogami i ruch rękoma), wykonaj dodatkowe mocne kopnięcie nogami.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Pełen cykl + dodatkowe kopnięcie",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Koordynacja",
                            Description = "Po każdym cyklu (kopnięcie nogami i ruch rękoma), wykonaj dodatkowy ruch rękoma.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Pełen cykl + dodatkowy ruch rękoma",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Wytrzymałość",
                            Description = "Skup się na utrzymaniu stałego tempa przez cały dystans.",
                            Distance = 200,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Równomierne tempo na dystansie",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 76,
                            Category = "Wytrzymałość",
                            Description = "Płyń 50m, odpoczywaj 15 sekund.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Wytrzymałość z krótkimi przerwami",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 77,
                            Category = "Wytrzymałość",
                            Description = "Utrzymuj kontrolę nad oddechem i tempem.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Długie dystanse w równym rytmie",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Wytrzymałość",
                            Description = "Spróbuj przepłynąć żabą 25m pod wodą.",
                            Distance = 25,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Żabo-Nurek",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 79,
                            Category = "Wytrzymałość",
                            Description = "Zmieniaj tempo co 50m, przechodząc z wolnego na szybkie.",
                            Distance = 250,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Naprzemienne tempo co 50",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 80,
                            Category = "Szybkość",
                            Description = "Daj z siebie wszystko przez 50m, odpoczywaj 30 sekund.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Sprinty z przerwami",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Szybkość",
                            Description = "Ćwicz szybkie starty i nawroty na krótkim dystansie.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dynamiczne starty z nawrotem",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Szybkość",
                            Description = "Zmieniaj intensywność co 25m. Szybko / luźno.",
                            Distance = 75,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Naprzemienne tempo sprintów",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 83,
                            Category = "Szybkość",
                            Description = "Płyń maksymalnym tempem przez każdy dystans.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Sprint",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Szybkość",
                            Description = "Staraj się utrzymać maksymalne tempo przez cały dystans.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Wydłużone sprinty",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Nogi",
                            Description = "Nogi muszą pracować jednocześnie. Skup się na rytmicznej pracy bioder i nóg.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Praca nóg z deską",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Nogi",
                            Description = "Połóż się na wyciągniętej ręce z przodu. Drugą trzymaj wzdłuż ciała. Utrzymuj biodra na powierzchni wody.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Kopnięcia nóg na boku",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Nogi",
                            Description = "Trzymaj ręce złączone w strzałce. Zrób krótką przerwę każdych 25m. Staraj się przepłynąć pod wodą jak najdłużej.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Pod wodą + strzałka",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 88,
                            Category = "Nogi",
                            Description = "Trzymaj ręce wzdłuż ciała. Co 3 kopnięcia nabieraj oddech, bez odrywania rąk.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Praca nóg + oddech",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Nogi",
                            Description = "Złącz ręce przed sobą w strzałce. Trzymaj brzuch napięty oraz pilnuj, aby stopy nie wychodziły nad wodę.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Naprzemienne kopnięcia z deski",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Ręce",
                            Description = "Ułóż ręce proste przed sobą. Delikatnie ugnij nadgarstki i pociągnij prostymi rękoma, aż do lini bioder. Zatrzymaj tam ręce wyprostowane i poczekaj, aż stracisz prędkość. ",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Pół - odepchnięcia pod wodą",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 91,
                            Category = "Ręce",
                            Description = "Trzymaj nogi stabilnie i skup się na ruchu rąk.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Praca rąk z pullboyem",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Ręce",
                            Description = "Pamiętaj, aby nie uginać ręki pod wodą. Nad wodą przenoś rękę bokiem. Skup się na pełnym zakresie ruchu jednej ręki. Zmieniaj rękę co 25m.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Praca jedną ręką na zmianę",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 93,
                            Category = "Ręce",
                            Description = "Skup się na pracy rąk. Wykomując nogi do kraula, łatwiej skupisz się na technice pracy rąk do delfina.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Kraulo-Delfin",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Ręce",
                            Description = "Wykonuj dokładankę płynąć jeden ruch jedną ręką, na zmianę z drugą.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dokładanka 1/2",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 95,
                            Category = "Koordynacja",
                            Description = "Połącz równomierne ruchy nóg i rąk.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Synchronizacja nóg i rąk",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 96,
                            Category = "Koordynacja",
                            Description = "Wykonuj naprzemiennie ruch rękoma. Zaczynaj parcę drugą ręką dopiero, gdy pierwsza znajdzie się wyprostowana z przodu obok drugiej ręki.Utrzymuj równomierny rytm przez cały cykl.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dokładanka z rękoma wyprostowanymi z przodu",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Koordynacja",
                            Description = "Wykonuj naprzemiennie ruch rękoma. Po każdym ruchu ręką, zatrzymaj je z przodu na 4 sekundy. Utrzymuj równomierny rytm przez cały cykl.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dokładanka z rękoma wyprostowanymi z przodu + zatrzymanie",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Koordynacja",
                            Description = "Po każdym cyklu (kopnięcie nogami i ruch rękoma), wykonaj dodatkowe mocne kopnięcie nogami.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Pełen cykl + dodatkowe kopnięcie",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 99,
                            Category = "Koordynacja",
                            Description = "Po każdym cyklu (kopnięcie nogami i ruch rękoma), wykonaj dodatkowy ruch rękoma.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Pełen cykl + dodatkowy ruch rękoma",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 100,
                            Category = "Wytrzymałość",
                            Description = "Skup się na utrzymaniu stałego rytmu i oddechu.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Pływanie w równym tempie",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 101,
                            Category = "Wytrzymałość",
                            Description = "Przepłyń 50, odpoczywaj 15 sekund, powtarzaj.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Tlenowe z krótkimi przerwami",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 102,
                            Category = "Wytrzymałość",
                            Description = "Utrzymuj równy rytm na długim dystansie.",
                            Distance = 150,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Długi dystans w stałym tempie",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 103,
                            Category = "Wytrzymałość",
                            Description = "Skup się na równomiernym oddechu co trzeci ruch ramion.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Seria z kontrolą oddechu",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 104,
                            Category = "Wytrzymałość",
                            Description = "Zmieniając tempo co 50m ( szybko/ wolno). ćwicz kontrolę nad wysiłkiem.",
                            Distance = 250,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Zmienność tempa na dystansie",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 105,
                            Category = "Szybkość",
                            Description = "Daj z siebie wszystko na krótkich dystansach.",
                            Distance = 25,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Sprinty 25m",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 106,
                            Category = "Szybkość",
                            Description = "Zmieniaj intensywność co 25m, przechodząc od sprintu do luźnego tempa.",
                            Distance = 75,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Naprzemienne sprinty i luźne tempo",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 107,
                            Category = "Szybkość",
                            Description = "Ćwicz szybkie starty i dynamiczne nawroty.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dynamiczne starty z nawrotem",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 108,
                            Category = "Szybkość",
                            Description = "Utrzymuj maksymalną intensywność przez 50m.",
                            Distance = 50,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Sprint 50m",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 109,
                            Category = "Szybkość",
                            Description = "Staraj się utrzymać maksymalne tempo przez cały dystans.",
                            Distance = 100,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Sprint na dłuższym dystansie",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 110,
                            Category = "Nogi",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 111,
                            Category = "Ręce",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 112,
                            Category = "Wytrzymałość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 113,
                            Category = "Koordynacja",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 114,
                            Category = "Szybkość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 115,
                            Category = "Nogi",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 116,
                            Category = "Ręce",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 117,
                            Category = "Wytrzymałość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 118,
                            Category = "Koordynacja",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 119,
                            Category = "Szybkość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Grzbiet"
                        },
                        new
                        {
                            Id = 120,
                            Category = "Nogi",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 121,
                            Category = "Ręce",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 122,
                            Category = "Wytrzymałość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 123,
                            Category = "Koordynacja",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 124,
                            Category = "Szybkość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 125,
                            Category = "Nogi",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 126,
                            Category = "Ręce",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 127,
                            Category = "Wytrzymałość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 128,
                            Category = "Koordynacja",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 129,
                            Category = "Szybkość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Kraul"
                        },
                        new
                        {
                            Id = 130,
                            Category = "Nogi",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 131,
                            Category = "Ręce",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 132,
                            Category = "Wytrzymałość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 133,
                            Category = "Koordynacja",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 134,
                            Category = "Szybkość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 135,
                            Category = "Nogi",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 136,
                            Category = "Ręce",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 137,
                            Category = "Wytrzymałość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 138,
                            Category = "Koordynacja",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 139,
                            Category = "Szybkość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Żaba"
                        },
                        new
                        {
                            Id = 140,
                            Category = "Nogi",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 141,
                            Category = "Ręce",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 142,
                            Category = "Wytrzymałość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 143,
                            Category = "Koordynacja",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 144,
                            Category = "Szybkość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Początkujący",
                            Name = "Dowolna kombinacja",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 145,
                            Category = "Nogi",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 146,
                            Category = "Ręce",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 147,
                            Category = "Wytrzymałość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 148,
                            Category = "Koordynacja",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Delfin"
                        },
                        new
                        {
                            Id = 149,
                            Category = "Szybkość",
                            Description = "Miksuj swoje ulubione ćwiczenia, pamiętając o technice i poprawnym ułożeniu ciała.",
                            Distance = 300,
                            IsDefault = true,
                            Level = "Zaawansowany",
                            Name = "Dowolna kombinacja",
                            Style = "Delfin"
                        });
                });

            modelBuilder.Entity("SplashTrainer.Models.SwimmingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDistance")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("TrainingDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SwimmingPlans");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SplashTrainer.Models.ActivityLog", b =>
                {
                    b.HasOne("SplashTrainer.Models.SwimmingPlan", "SwimmingPlan")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("SwimmingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwimmingPlan");
                });

            modelBuilder.Entity("SplashTrainer.Models.PlanExercise", b =>
                {
                    b.HasOne("SplashTrainer.Models.SwimmingExercise", "SwimmingExercise")
                        .WithMany()
                        .HasForeignKey("SwimmingExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SplashTrainer.Models.SwimmingPlan", "SwimmingPlan")
                        .WithMany("Exercises")
                        .HasForeignKey("SwimmingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SwimmingExercise");

                    b.Navigation("SwimmingPlan");
                });

            modelBuilder.Entity("SplashTrainer.Models.SwimmingPlan", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
